
export const countryMap = [{ country: 'AFGHANISTAN', value: 'AF' },
{ country: 'ALBANIA', value: 'AL' },
{ country: 'ALGERIA', value: 'DZ' },
{ country: 'AMERICAN SAMOA', value: 'AS' },
{ country: 'ANDORRA', value: 'AD' },
{ country: 'ANGOLA', value: 'AO' },
{ country: 'ANTARCTICA', value: 'AQ' },
{ country: 'ANTIGUA AND BARBUDA', value: 'AG' },
{ country: 'ARGENTINA', value: 'AR' },
{ country: 'ARMENIA', value: 'AM' },
{ country: 'ARUBA', value: 'AW' },
{ country: 'AUSTRALIA', value: 'AU' },
{ country: 'AUSTRIA', value: 'AT' },
{ country: 'AZERBAIJAN', value: 'AZ' },
{ country: 'BAHAMAS', value: 'BS' },
{ country: 'BAHRAIN', value: 'BH' },
{ country: 'BANGLADESH', value: 'BD' },
{ country: 'BARBADOS', value: 'BB' },
{ country: 'BELARUS', value: 'BY' },
{ country: 'BELGIUM', value: 'BE' },
{ country: 'BELIZE', value: 'BZ' },
{ country: 'BENIN', value: 'BJ' },
{ country: 'BERMUDA', value: 'BM' },
{ country: 'BHUTAN', value: 'BT' },
{ country: 'BOLIVIA', value: 'BO' },
{ country: 'BOSNIA AND HERZEGOVINA', value: 'BA' },
{ country: 'BOTSWANA', value: 'BW' },
{ country: 'BOUVET ISLAND', value: 'BV' },
{ country: 'BRAZIL', value: 'BR' },
{ country: 'BRITISH INDIAN OCEAN TERRITORY', value: 'IO' },
{ country: 'BRUNEI DARUSSALAM', value: 'BN' },
{ country: 'BULGARIA', value: 'BG' },
{ country: 'BURKINA FASO', value: 'BF' },
{ country: 'BURUNDI', value: 'BI' },
{ country: 'CAMBODIA', value: 'KH' },
{ country: 'CAMEROON', value: 'CM' },
{ country: 'CANADA', value: 'CA' },
{ country: 'CAPE VERDE', value: 'CV' },
{ country: 'CAYMAN ISLANDS', value: 'KY' },
{ country: 'CENTRAL AFRICAN REPUBLIC', value: 'CF' },
{ country: 'CHAD', value: 'TD' },
{ country: 'CHILE', value: 'CL' },
{ country: 'CHINA', value: 'CN' },
{ country: 'CHRISTMAS ISLAND', value: 'CX' },
{ country: 'COCOS (KEELING) ISLANDS', value: 'CC' },
{ country: 'COLOMBIA', value: 'CO' },
{ country: 'COMOROS', value: 'KM' },
{ country: 'CONGO', value: 'CG' },
{ country: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', value: 'CD' },
{ country: 'COOK ISLANDS', value: 'CK' },
{ country: 'COSTA RICA', value: 'CR' },
{ country: 'CÔTE D\'IVOIRE', value: 'CI' },
{ country: 'CROATIA', value: 'HR' },
{ country: 'CUBA', value: 'CU' },
{ country: 'CYPRUS', value: 'CY' },
{ country: 'CZECH REPUBLIC', value: 'CZ' },
{ country: 'DENMARK', value: 'DK' },
{ country: 'DJIBOUTI', value: 'DJ' },
{ country: 'DOMINICA', value: 'DM' },
{ country: 'DOMINICAN REPUBLIC', value: 'DO' },
{ country: 'ECUADOR', value: 'EC' },
{ country: 'EGYPT', value: 'EG' },
{ country: 'EL SALVADOR', value: 'SV' },
{ country: 'EQUATORIAL GUINEA', value: 'GQ' },
{ country: 'ERITREA', value: 'ER' },
{ country: 'ESTONIA', value: 'EE' },
{ country: 'ETHIOPIA', value: 'ET' },
{ country: 'FALKLAND ISLANDS (MALVINAS)', value: 'FK' },
{ country: 'FAROE ISLANDS', value: 'FO' },
{ country: 'FIJI', value: 'FJ' },
{ country: 'FINLAND', value: 'FI' },
{ country: 'FRANCE', value: 'FR' },
{ country: 'FRENCH GUIANA', value: 'GF' },
{ country: 'FRENCH POLYNESIA', value: 'PF' },
{ country: 'FRENCH SOUTHERN TERRITORIES', value: 'TF' },
{ country: 'GABON', value: 'GA' },
{ country: 'GAMBIA', value: 'GM' },
{ country: 'GEORGIA', value: 'GE' },
{ country: 'GERMANY', value: 'DE' },
{ country: 'GHANA', value: 'GH' },
{ country: 'GIBRALTAR', value: 'GI' },
{ country: 'GREECE', value: 'GR' },
{ country: 'GREENLAND', value: 'GL' },
{ country: 'GRENADA', value: 'GD' },
{ country: 'GUADELOUPE', value: 'GP' },
{ country: 'GUAM', value: 'GU' },
{ country: 'GUATEMALA', value: 'GT' },
{ country: 'GUINEA', value: 'GN' },
{ country: 'GUINEA-BISSAU', value: 'GW' },
{ country: 'GUYANA', value: 'GY' },
{ country: 'HAITI', value: 'HT' },
{ country: 'HEARD ISLAND AND MCDONALD ISLANDS', value: 'HM' },
{ country: 'HONDURAS', value: 'HN' },
{ country: 'HONG KONG', value: 'HK' },
{ country: 'HUNGARY', value: 'HU' },
{ country: 'ICELAND', value: 'IS' },
{ country: 'INDIA', value: 'IN' },
{ country: 'INDONESIA', value: 'ID' },
{ country: 'IRAN, ISLAMIC REPUBLIC OF', value: 'IR' },
{ country: 'IRAQ', value: 'IQ' },
{ country: 'IRELAND', value: 'IE' },
{ country: 'ISRAEL', value: 'IL' },
{ country: 'ITALY', value: 'IT' },
{ country: 'JAMAICA', value: 'JM' },
{ country: 'JAPAN', value: 'JP' },
{ country: 'JORDAN', value: 'JO' },
{ country: 'KAZAKHSTAN', value: 'KZ' },
{ country: 'KENYA', value: 'KE' },
{ country: 'KIRIBATI', value: 'KI' },
{ country: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', value: 'KP' },
{ country: 'KOREA, REPUBLIC OF', value: 'KR' },
{ country: 'KUWAIT', value: 'KW' },
{ country: 'KYRGYZSTAN', value: 'KG' },
{ country: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC (LAOS)', value: 'LA' },
{ country: 'LATVIA', value: 'LV' },
{ country: 'LEBANON', value: 'LB' },
{ country: 'LESOTHO', value: 'LS' },
{ country: 'LIBERIA', value: 'LR' },
{ country: 'LIBYA, STATE OF', value: 'LY' },
{ country: 'LIECHTENSTEIN', value: 'LI' },
{ country: 'LITHUANIA', value: 'LT' },
{ country: 'LUXEMBOURG', value: 'LU' },
{ country: 'MACAO', value: 'MO' },
{ country: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', value: 'MK' },
{ country: 'MADAGASCAR', value: 'MG' },
{ country: 'MALAWI', value: 'MW' },
{ country: 'MALAYSIA', value: 'MY' },
{ country: 'MALDIVES', value: 'MV' },
{ country: 'MALI', value: 'ML' },
{ country: 'MALTA', value: 'MT' },
{ country: 'MARSHALL ISLANDS', value: 'MH' },
{ country: 'MARTINIQUE', value: 'MQ' },
{ country: 'MAURITANIA', value: 'MR' },
{ country: 'MAURITIUS', value: 'MU' },
{ country: 'MAYOTTE', value: 'YT' },
{ country: 'MEXICO', value: 'MX' },
{ country: 'MICRONESIA, FEDERATED STATES OF', value: 'FM' },
{ country: 'MOLDOVA, REPUBLIC OF', value: 'MD' },
{ country: 'MONACO', value: 'MC' },
{ country: 'MONGOLIA', value: 'MN' },
{ country: 'MONTENEGRO', value: 'ME' },
{ country: 'MONTSERRAT', value: 'MS' },
{ country: 'MOROCCO', value: 'MA' },
{ country: 'MOZAMBIQUE', value: 'MZ' },
{ country: 'MYANMAR', value: 'MM' },
{ country: 'NAMIBIA', value: 'NA' },
{ country: 'NAURU', value: 'NR' },
{ country: 'NEPAL, FEDERAL DEMOCRATIC REPUBLIC OF', value: 'NP' },
{ country: 'NETHERLANDS', value: 'NL' },
{ country: 'NETHERLANDS ANTILLES', value: 'AN' },
{ country: 'NEW CALEDONIA', value: 'NC' },
{ country: 'NEW ZEALAND', value: 'NZ' },
{ country: 'NICARAGUA', value: 'NI' },
{ country: 'NIGER', value: 'NE' },
{ country: 'NIGERIA', value: 'NG' },
{ country: 'NIUE', value: 'NU' },
{ country: 'NORFOLK ISLAND', value: 'NF' },
{ country: 'NORTHERN MARIANA ISLANDS', value: 'MP' },
{ country: 'NORWAY', value: 'NO' },
{ country: 'OMAN', value: 'OM' },
{ country: 'PAKISTAN', value: 'PK' },
{ country: 'PALAU', value: 'PW' },
{ country: 'PALESTINE, STATE OF', value: 'PS' },
{ country: 'PANAMA', value: 'PA' },
{ country: 'PAPUA NEW GUINEA', value: 'PG' },
{ country: 'PARAGUAY', value: 'PY' },
{ country: 'PERU', value: 'PE' },
{ country: 'PHILIPPINES', value: 'PH' },
{ country: 'PITCAIRN', value: 'PN' },
{ country: 'POLAND', value: 'PL' },
{ country: 'PORTUGAL', value: 'PT' },
{ country: 'PUERTO RICO', value: 'PR' },
{ country: 'QATAR', value: 'QA' },
{ country: 'RÉUNION', value: 'RE' },
{ country: 'ROMANIA', value: 'RO' },
{ country: 'RUSSIAN FEDERATION', value: 'RU' },
{ country: 'RWANDA', value: 'RW' },
{ country: 'SAINT HELENA', value: 'SH' },
{ country: 'SAINT KITTS AND NEVIS', value: 'KN' },
{ country: 'SAINT LUCIA', value: 'LC' },
{ country: 'SAINT PIERRE AND MIQUELON', value: 'PM' },
{ country: 'SAINT VINCENT AND THE GRENADINES', value: 'VC' },
{ country: 'SAMOA', value: 'WS' },
{ country: 'SAN MARINO', value: 'SM' },
{ country: 'SAO TOME AND PRINCIPE', value: 'ST' },
{ country: 'SAUDI ARABIA', value: 'SA' },
{ country: 'SENEGAL', value: 'SN' },
{ country: 'SERBIA', value: 'RS' },
{ country: 'SEYCHELLES', value: 'SC' },
{ country: 'SIERRA LEONE', value: 'SL' },
{ country: 'SINGAPORE', value: 'SG' },
{ country: 'SLOVAKIA', value: 'SK' },
{ country: 'SLOVENIA', value: 'SI' },
{ country: 'SOLOMON ISLANDS', value: 'SB' },
{ country: 'SOMALIA', value: 'SO' },
{ country: 'SOUTH AFRICA', value: 'ZA' },
{ country: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', value: 'GS' },
{ country: 'SOUTH SUDAN', value: 'SS' },
{ country: 'SPAIN', value: 'ES' },
{ country: 'SRI LANKA', value: 'LK' },
{ country: 'SUDAN', value: 'SD' },
{ country: 'SURINAME', value: 'SR' },
{ country: 'SVALBARD AND JAN MAYEN', value: 'SJ' },
{ country: 'SWAZILAND', value: 'SZ' },
{ country: 'SWEDEN', value: 'SE' },
{ country: 'SWITZERLAND', value: 'CH' },
{ country: 'SYRIAN ARAB REPUBLIC', value: 'SY' },
{ country: 'TAIWAN', value: 'TW' },
{ country: 'TAJIKISTAN', value: 'TJ' },
{ country: 'TANZANIA, UNITED REPUBLIC OF', value: 'TZ' },
{ country: 'THAILAND', value: 'TH' },
{ country: 'TIMOR-LESTE', value: 'TL' },
{ country: 'TOGO', value: 'TG' },
{ country: 'TOKELAU', value: 'TK' },
{ country: 'TONGA', value: 'TO' },
{ country: 'TRINIDAD AND TOBAGO', value: 'TT' },
{ country: 'TUNISIA', value: 'TN' },
{ country: 'TURKEY', value: 'TR' },
{ country: 'TURKMENISTAN', value: 'TM' },
{ country: 'TURKS AND CAICOS ISLANDS', value: 'TC' },
{ country: 'TUVALU', value: 'TV' },
{ country: 'UGANDA', value: 'UG' },
{ country: 'UKRAINE', value: 'UA' },
{ country: 'UNITED ARAB EMIRATES', value: 'AE' },
{ country: 'UNITED KINGDOM', value: 'GB' },
{ country: 'UNITED STATES', value: 'US' },
{ country: 'UNITED STATES MINOR OUTLYING ISLANDS', value: 'UM' },
{ country: 'URUGUAY', value: 'UY' },
{ country: 'UZBEKISTAN', value: 'UZ' },
{ country: 'VANUATU', value: 'VU' },
{ country: 'VENEZUELA', value: 'VE' },
{ country: 'VIET NAM', value: 'VN' },
{ country: 'VIRGIN ISLANDS, BRITISH', value: 'VG' },
{ country: 'VIRGIN ISLANDS, U.S.', value: 'VI' },
{ country: 'WALLIS AND FUTUNA', value: 'WF' },
{ country: 'WESTERN SAHARA', value: 'EH' },
{ country: 'YEMEN', value: 'YE' },
{ country: 'ZAMBIA', value: 'ZM' },
{ country: 'ZIMBABWE', value: 'ZW' }]