export const  languageMap = [
    { lang: 'Abkhazian', value: 'ab' },
    { lang: 'Afrikaans', value: 'af' },
    { lang: 'Aragonese', value: 'an' },
    { lang: 'Arabic', value: 'ar' },
    { lang: 'Assamese', value: 'as' },
    { lang: 'Azerbaijani', value: 'az' },
    { lang: 'Belarusian', value: 'be' },
    { lang: 'Bulgarian', value: 'bg' },
    { lang: 'Bengali', value: 'bn' },
    { lang: 'Tibetan', value: 'bo' },
    { lang: 'Breton', value: 'br' },
    { lang: 'Bosnian', value: 'bs' },
    { lang: 'Catalan / Valencian', value: 'ca' },
    { lang: 'Chechen', value: 'ce' },
    { lang: 'Corsican', value: 'co' },
    { lang: 'Czech', value: 'cs' },
    { lang: 'Church Slavic', value: 'cu' },
    { lang: 'Welsh', value: 'cy' },
    { lang: 'Danish', value: 'da' },
    { lang: 'German', value: 'de' },
    { lang: 'Greek', value: 'el' },
    { lang: 'English', value: 'en' },
    { lang: 'Esperanto', value: 'eo' },
    { lang: 'Spanish / Castilian', value: 'es' },
    { lang: 'Estonian', value: 'et' },
    { lang: 'Basque', value: 'eu' },
    { lang: 'Persian', value: 'fa' },
    { lang: 'Finnish', value: 'fi' },
    { lang: 'Fijian', value: 'fj' },
    { lang: 'Faroese', value: 'fo' },
    { lang: 'French', value: 'fr' },
    { lang: 'Western Frisian', value: 'fy' },
    { lang: 'Irish', value: 'ga' },
    { lang: 'Gaelic / Scottish Gaelic', value: 'gd' },
    { lang: 'Galician', value: 'gl' },
    { lang: 'Manx', value: 'gv' },
    { lang: 'Hebrew', value: 'he' },
    { lang: 'Hindi', value: 'hi' },
    { lang: 'Croatian', value: 'hr' },
    { lang: 'Haitian; Haitian Creole', value: 'ht' },
    { lang: 'Hungarian', value: 'hu' },
    { lang: 'Armenian', value: 'hy' },
    { lang: 'Indonesian', value: 'id' },
    { lang: 'Icelandic', value: 'is' },
    { lang: 'Italian', value: 'it' },
    { lang: 'Japanese', value: 'ja' },
    { lang: 'Javanese', value: 'jv' },
    { lang: 'Georgian', value: 'ka' },
    { lang: 'Kongo', value: 'kg' },
    { lang: 'Korean', value: 'ko' },
    { lang: 'Kurdish', value: 'ku' },
    { lang: 'Cornish', value: 'kw' },
    { lang: 'Kirghiz', value: 'ky' },
    { lang: 'Latin', value: 'la' },
    { lang: 'Luxembourgish; Letzeburgesch', value: 'lb' },
    { lang: 'Limburgan; Limburger; Limburgish', value: 'li' },
    { lang: 'Lingala', value: 'ln' },
    { lang: 'Lithuanian', value: 'lt' },
    { lang: 'Latvian', value: 'lv' },
    { lang: 'Malagasy', value: 'mg' },
    { lang: 'Macedonian', value: 'mk' },
    { lang: 'Mongolian', value: 'mn' },
    { lang: 'Moldavian', value: 'mo' },
    { lang: 'Malay', value: 'ms' },
    { lang: 'Maltese', value: 'mt' },
    { lang: 'Burmese', value: 'my' },
    { lang: 'Norwegian (Bokmål)', value: 'nb' },
    { lang: 'Nepali', value: 'ne' },
    { lang: 'Dutch', value: 'nl' },
    { lang: 'Norwegian (Nynorsk)', value: 'nn' },
    { lang: 'Norwegian', value: 'no' },
    { lang: 'Occitan (post 1500); Provençal', value: 'oc' },
    { lang: 'Polish', value: 'pl' },
    { lang: 'Portuguese', value: 'pt' },
    { lang: 'Raeto-Romance', value: 'rm' },
    { lang: 'Romanian', value: 'ro' },
    { lang: 'Russian', value: 'ru' },
    { lang: 'Sardinian', value: 'sc' },
    { lang: 'Northern Sami', value: 'se' },
    { lang: 'Slovak', value: 'sk' },
    { lang: 'Slovenian', value: 'sl' },
    { lang: 'Somali', value: 'so' },
    { lang: 'Albanian', value: 'sq' },
    { lang: 'Serbian', value: 'sr' },
    { lang: 'Swedish', value: 'sv' },
    { lang: 'Swahili', value: 'sw' },
    { lang: 'Turkmen', value: 'tk' },
    { lang: 'Turkish', value: 'tr' },
    { lang: 'Tahitian', value: 'ty' },
    { lang: 'Ukrainian', value: 'uk' },
    { lang: 'Urdu', value: 'ur' },
    { lang: 'Uzbek', value: 'uz' },
    { lang: 'Vietnamese', value: 'vi' },
    { lang: 'Volapük', value: 'vo' },
    { lang: 'Yiddish', value: 'yi' },
    { lang: 'Chinese (simplified)', value: 'zh-hans' },
    { lang: 'Thai', value: 'th' },
  ]